Add feature upgradable read
stjepang/async-rwlock pull request #4
Opened 2020-09-19 20:42 UTC by librelois

Add upgradable read lock conform to lock api definition : https://docs.rs/lock_api/0.4.1/lock_api/struct.RwLock.html#method.upgradable_read

It' s a very useful feature to perform writing transactions that minimize the time of blocking readers. Data changes are actually written only when committing the transaction, the lock upgrade is only done at the time of commit to minimize the time of blocking readers (And if the transaction is aborted, the readers are never blocked).

2020-09-20 11:13 UTC, stjepang requested changes
This is great! And much simpler than I thought it would be :)

I'm leaving some comments below, mostly nits.

Have you perhaps thought of also adding methods `try_upgrade()` and `downgrade()` (doesn't have to be in this PR)? I see `parking_lot` has those, and they seem like logical extensions.

2020-09-20 11:13 UTC, stjepang commented on src/lib.rs
> +        // Set `WRITER_BIT` and decrement the number of readers at the mean time.
```suggestion
        // Set `WRITER_BIT` and decrement the number of readers at the same time.
```

2020-09-20 11:13 UTC, stjepang commented on src/lib.rs
> +        //Trigger the "no writer" event.
```suggestion
        // Trigger the "no writer" event.
```

2020-09-20 11:13 UTC, stjepang commented on tests/upgradable.rs
> +    async move {
```suggestion
            async move {
```

2020-09-20 11:13 UTC, stjepang commented on tests/upgradable.rs
> +
```suggestion

```

2020-09-20 11:13 UTC, stjepang commented on src/lib.rs
> +        let guard = RwLockWriteGuard(self.0, self.1.take().unwrap_or_else(|| unreachable!()));
```suggestion
        let guard = RwLockWriteGuard(self.0, self.1.take().unwrap();
```

2020-09-20 11:13 UTC, stjepang commented on src/lib.rs
> +    pub async fn upgrade(mut self) -> RwLockWriteGuard<'a, T> {
Let's change this to:
```suggestion
    pub async fn upgrade(this: Self) -> RwLockWriteGuard<'a, T> {
```

See `parking_lot`'s signature of the equivalent function: https://docs.rs/lock_api/0.4.0/lock_api/struct.RwLockUpgradableReadGuard.html#method.upgrade

The reason for that is we don't want `.upgrade()` on `RwLockUpgradableReadGuard` to clash with `.upgrade()` on the inner type `T`, if it has a method with the same name.

Generally speaking, this rule applies to all types implementing `Deref` (like `RwLockUpgradableReadGuard` does).

2020-09-20 11:22 UTC, stjepang commented
By the way, how would you feel about `async-mutex`, `async-rwlock`, `async-semaphore`, and `async-barrier` being merged into `async-lock` after this PR?

The synchronization primitives were broken into small crates as I was implementing them one by time a long time ago, but now they're becoming a cohesive unit so it would make maintenance slightly easier if they were grouped into the main `async-lock` crate.

2020-09-20 15:04 UTC, librelois commented on src/lib.rs
> +        let guard = RwLockWriteGuard(self.0, self.1.take().unwrap_or_else(|| unreachable!()));
That's because I'm used to working with lint `deny(clippy::unwrap_used)` :)

In this case we can optimize with `unwrap_or_else(|| unsafe { unreachable_unchecked() })` because we know that the option can never be None: the upgrade method can't be called twice because it "consumes" the guard.

2020-09-20 15:18 UTC, librelois commented
> This is great! And much simpler than I thought it would be :)

Yes I was surprised to discover that no async implementation offered this very useful feature and rather simple to implement, so I decided to do it :)

> I'm leaving some comments below, mostly nits.

I treated all of them except 1 (see my answer).

> Have you perhaps thought of also adding methods try_upgrade() and downgrade() (doesn't have to be in this PR)? I see parking_lot has those, and they seem like logical extensions.

I added `try_upgrade()`, I prefer that the downgrade methods are added in another PR :)

> By the way, how would you feel about async-mutex, async-rwlock, async-semaphore, and async-barrier being merged into async-lock after this PR?

I think it is important that users can choose only the sync primitives they need. This can be done by a single crate with optional features but in my experience this is harder to maintain.

I think that for easy maintenance while allowing users to take only what they need, the best is to do like [crossbeam](https://github.com/crossbeam-rs/crossbeam): a meta-crate that just exposes the features of the "sub-crates", all in the same git repository (it's mostly the fact of having several repositories that is a pain).

2020-09-20 15:36 UTC, stjepang commented
> I think it is important that users can choose only the sync primitives they need. This can be done by a single crate with optional features but in my experience this is harder to maintain.

Well, usually I'd agree with you but this case is a bit special. Here are the crates in question:

- https://docs.rs/async-barrier/1.0.1/src/async_barrier/lib.rs.html#1-139
- https://docs.rs/async-mutex/1.3.0/src/async_mutex/lib.rs.html#1-455
- https://docs.rs/async-semaphore/1.1.0/src/async_semaphore/lib.rs.html#1-196

They are all quite small (most of the code is just docs) and they all look the same, simply using `event-listener` + some atomics, so it's not like they add extra dependencies, increase code size, or measurably affect compilation times...

2020-09-20 15:38 UTC, stjepang commented on src/lib.rs
> +        let guard = RwLockWriteGuard(self.0, self.1.take().unwrap_or_else(|| unreachable!()));
Another option is to do `.expect("the mutex must exist")` or something like that. I'm not too keen on `unreachable_unchecked()` because I'd like to minimize the amount of unsafe code, wherever possible.

2020-09-20 16:09 UTC, librelois commented
> They are all quite small (most of the code is just docs) and they all look the same, simply using event-listener + some atomics, so it's not like they add extra dependencies, increase code size, or measurably affect compilation times...

The same could be said for the different `crossbeam-*` crates, for 90% of projects the extra cost is negligible, but in some particular cases there can be radical constraints on the size of the final binary, and in these cases there are no small savings :)

Also merging these crates makes them invisible. If I'm looking for an async semaphore I won't look for "async lock" but "async semaphore" ;)

Finally merging these crates would mean that the users of the sub-crates would no longer benefit from the updates, so we would have to yanked all the sub-crates for security, but it means a breaking change imposed for all the projects that use it.

You asked my opinion so I'm giving it to you, personally I think it's a good design to keep several crates separate, but I'd put them together in a single git repository :)

2020-09-20 16:16 UTC, stjepang commented
Makes sense, thanks for the honest opinion :) I think I will just merge those repositories together and add a note to the readmes.

2020-09-20 17:09 UTC, librelois commented on src/lib.rs
> +        let guard = RwLockWriteGuard(self.0, self.1.take().unwrap_or_else(|| unreachable!()));
> I'd like to minimize the amount of unsafe code, wherever possible.

Yes, I am also in favor of minimizing unsafe blocks, except when banning them necessarily represents an additional cost in terms of performance. If you have an idea to do without unsafe and without extra cost, I'm interested :)

Here by the way the Option itself is an unnecessary extra cost, I could get rid of it using [ManuallyDrop](https://doc.rust-lang.org/stable/std/mem/struct.ManuallyDrop) but it would require a change in async-mutex (adding a function with a signature like `pub unsafe fn from_source(source: &'a Mutex<T>) -> MutexGuard<'a, T>`).

The irony is that we could get by without unsafe and at no extra cost if the 2 crates were unified into one, but from my point of view this is not a good enough reason to do so :p 

Hunting unsafe blocks should not make us do just anything, if maximizing performance is part of our goals, then some unsafe blocks are inevitable.

For the moment I'm going to use an expect as you ask me, because it allows us to move forward, we can talk about performance later :)

2020-09-20 17:15 UTC, librelois commented
> Makes sense, thanks for the honest opinion :)

You're welcome. I prefer to be honest even though it doesn't feel good. Afterwards, if my opinion is not followed, it's okay, I adapt :)

2020-09-20 19:48 UTC, librelois commented on src/lib.rs
> +        let guard = RwLockWriteGuard(self.0, self.1.take().unwrap_or_else(|| unreachable!()));
@stjepang I finally found a way to do without the Option and without unsafe code, I just push force :)

2020-09-21 12:59 UTC, stjepang approved these changes
Looks good, thanks again! :)

2020-09-21 12:59 UTC, merged

2020-09-21 13:49 UTC, stjepang commented
Published a new version of the crate that includes this PR.

2020-09-21 16:09 UTC, librelois commented
> Have you perhaps thought of also adding methods try_upgrade() and downgrade() (doesn't have to be in this PR)? I see parking_lot has those, and they seem like logical extensions.

I can do a PR for the downgrade functions, would you prefer I wait for the crates gathering in the `async_lock` repository? :)

2020-09-21 16:59 UTC, stjepang commented
A PR would be welcome :) let's move over to the `async-lock` repository. I have merged all the crates together:

https://github.com/stjepang/async-lock